# -*- coding: utf-8 -*-
"""exercicio_regressao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxG1zs-pEI-owFM7oKb_SU5Uu1eZfsC-
"""

# Dados para a dinâmica
import pandas as pd

# Histórico dos meses anteriores
dados_marketing = {
    'Investimento_Anuncios': [1000, 2000, 3000, 4000, 5000],
    'Faturamento': [15000, 25000, 36000, 48000, 58000]
}
tabela = pd.DataFrame(dados_marketing)
print("Dados:")
display(tabela)

X = tabela[['Investimento_Anuncios']]
y = tabela['Faturamento']

# Gráfico de dispersão
tabela.plot(kind='scatter', x='Investimento_Anuncios', y='Faturamento',
            color='purple', title='Relação: Investimento Anuncios X Faturamento')

# Preparação e Treino
from sklearn.linear_model import LinearRegression

modelo = LinearRegression()

modelo.fit(X,y)

# A pergunta do Diretor: O que acontece se investirmos 8000?

faturamento = float(input("Qual é o investimento?\n"))
#Queremos saber o preço de uma casa de 90m2
faturamento_investimento = pd.DataFrame({'Investimento_Anuncios': [faturamento]})

#Usamos o método .predict() para o código fazer a predição
preco_previsto = modelo.predict(faturamento_investimento)

preco = f"{preco_previsto[0]:.2f}"
print("O valor de faturamento será de:", preco)